In [1]:
import numpy  as np

In [3]:
myList = [1,2,3,4,5]
myList

[1, 2, 3, 4, 5]

In [4]:
ar = np.array(myList)
ar

array([1, 2, 3, 4, 5])

In [5]:
myMaths = [[1,2,3],[4,5,6],[7,8,9]]
myMaths

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
myArr = np.array(myMaths)
myArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,12,3)

array([ 0.,  6., 12.])

In [25]:
np.linspace(1,12,4)

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])

In [21]:
np.linspace(0,12,15)

array([ 0.        ,  0.85714286,  1.71428571,  2.57142857,  3.42857143,
        4.28571429,  5.14285714,  6.        ,  6.85714286,  7.71428571,
        8.57142857,  9.42857143, 10.28571429, 11.14285714, 12.        ])

In [24]:
#geomspace, logspace
np.geomspace(1,12,4)

array([ 1.        ,  2.28942849,  5.24148279, 12.        ])

In [26]:
np.logspace(1,12,4)

array([1.00000000e+01, 4.64158883e+04, 2.15443469e+08, 1.00000000e+12])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.random.rand(5)

array([0.49841208, 0.33504576, 0.10897153, 0.75548348, 0.55928862])

In [29]:
np.random.rand(4,5)

array([[0.78123771, 0.14771213, 0.37706807, 0.83079965, 0.83524231],
       [0.85261903, 0.93948194, 0.9482167 , 0.56000743, 0.54270326],
       [0.71857106, 0.57440913, 0.19298361, 0.90851201, 0.59945809],
       [0.12013896, 0.26315437, 0.05771198, 0.33236612, 0.98255399]])

In [32]:
#for gaussian distribution
np.random.randn(3)

array([-1.4398502 ,  0.55294005,  0.82092128])

In [33]:
np.random.randn(4,4)

array([[-1.3393427 , -0.12799991, -0.63606462,  0.28940028],
       [-0.16429118, -0.92164617, -0.39277556, -1.17983783],
       [ 1.33677623,  1.99950314, -0.45080159,  0.74126634],
       [ 2.16158434,  0.49877997, -0.12902724,  1.02633776]])

In [41]:
np.random.randint(0,10,(4,4))

array([[1, 6, 8, 9],
       [3, 5, 0, 0],
       [8, 2, 7, 0],
       [7, 0, 0, 5]])

In [45]:
#
ar1 = np.arange(25)
ar2 = np.random.randint(0,50,10)

In [46]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ar2

array([34,  0,  2, 14, 47, 21, 27, 25, 49, 31])

In [51]:
ar1.reshape(5,8)#you have to fill with the range of array you have created

ValueError: cannot reshape array of size 25 into shape (5,8)

In [49]:
ar1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ar2.max()

49

In [54]:
ar2.min()

0

In [55]:
#index location of max value
ar2.argmax()

8

In [57]:
ar2.argmin()

1

In [59]:
ar1.shape

(25,)

In [62]:
ar3 = ar1.reshape(5,5)

In [63]:
ar3.shape

(5, 5)

In [64]:
ar1.shape

(25,)

In [67]:
ar1.dtype

dtype('int32')

#NUMPY ARRAY INDEXING

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[8]

8

In [73]:
arr[:5]

array([0, 1, 2, 3, 4])

In [74]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [75]:
arr[:5] = 100

In [76]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [78]:
arr = np.arange(0,11)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
slice_arr = arr[:5] = 99

In [84]:
slice_arr

99

In [81]:
slice_arr = 99

In [82]:
slice_arr

99

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr_slice = arr[:5]

In [89]:
arr_slice

array([0, 1, 2, 3, 4])

In [90]:
arr_slice[:] = 99

In [91]:
arr_slice

array([99, 99, 99, 99, 99])

In [92]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [110]:
arr = np.arange(0,11)

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
arr_copy = arr.copy()

In [113]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr_slice =  arr_copy[:5]

In [115]:
arr_slice

array([0, 1, 2, 3, 4])

In [116]:
arr_slice[:] = 99

In [117]:
arr_slice

array([99, 99, 99, 99, 99])

In [118]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
#2d array --- 

In [121]:
ar_2d = np.array([[23,21,45],[54,23,34],[11,64,25]])

In [122]:
ar_2d

array([[23, 21, 45],
       [54, 23, 34],
       [11, 64, 25]])

In [123]:
ar_2d[1][2]

34

In [124]:
ar_2d[1,2]

34

In [126]:
ar_2d[:2, 1:]

array([[21, 45],
       [23, 34]])

In [127]:
ar_2d[1:, 1:]

array([[23, 34],
       [64, 25]])

In [128]:
#conditional selection


In [129]:
arr = np.arange(0,11)

In [135]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [140]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [141]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [142]:
arr[arr<3]

array([0, 1, 2])

In [143]:
arr_2d = np.arange(0,50).reshape(5,10)

In [144]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
arr_2d[1:3,1:3]

array([[11, 12],
       [21, 22]])

In [146]:
arr_2d[1:4,3:5]

array([[13, 14],
       [23, 24],
       [33, 34]])

In [147]:
#Numpy Operations
#array with array
#array with scalars
#universal array functions

In [148]:
arr = np.arange(0,11)

In [149]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [151]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [152]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [153]:
arr+100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [154]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [155]:
arr* 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [156]:
arr/arr

<ipython-input-156-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [157]:
1/arr

<ipython-input-157-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [158]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [161]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [163]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [165]:
np.max(arr)

10

In [166]:
np.min(arr)

0

In [167]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [169]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [170]:
np.log(arr)

<ipython-input-170-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [171]:
np.cbrt(arr)

array([0.        , 1.        , 1.25992105, 1.44224957, 1.58740105,
       1.70997595, 1.81712059, 1.91293118, 2.        , 2.08008382,
       2.15443469])